use_frameworks!

platform :ios, '9.0'

target 'MyCocoaPodTest_Example' do
  pod 'MyCocoaPodTest', :path => '../'

  target 'MyCocoaPodTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
